name: Go build on push

on:
  push:
    branches: [ xray ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Install packr2
      run: go get github.com/gobuffalo/packr/v2/packr2 

    - name: Run packer
      run: packr2

    - name: Run mod tidy
      run: go mod tidy

    - name: Build
      run: go build -ldflags "-s -w" .

    - name: Clean
      run: packr2 clean
