name: Go

on:
  push:
    branches: [ xray ]
  pull_request:
    branches: [ xray ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        ref: xray

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Install packr2
      run: |
        go get -u github.com/gobuffalo/packr/v2/...
        go get -u github.com/gobuffalo/packr/v2/packr2
        which packr2

    - name: Build xxxray binary file
      run: |
        packr2
        go build -ldflags "-s -w -X 'trojan/xray.MVersion=`git describe --tags $(git rev-list --tags --max-count=1)`' -X 'trojan/xray.BuildDate=`TZ=Asia/Shanghai date "+%Y%m%d-%H%M"`' -X 'trojan/xray.GoVersion=`go version|awk '{print $3,$4}'`' -X 'trojan/xray.GitVersion=`git rev-parse HEAD`'" -o "result/xxxray" .
        touch result/xxxray
        packr2 clean

    - name: Upload result directory
      uses: actions/upload-artifact@main
      with:
        name: xxxray
        path: result

    - name: Upload to release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: result/xxxray

    - name: Test
      run: go test -v ./...
    
